version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: filevault-postgres
    environment:
      POSTGRES_DB: filevault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: filevault-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/filevault?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 8080
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 52428800
      RATE_LIMIT: 2
      STORAGE_QUOTA: 10485760
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: filevault-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api/v1
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: