services:
  postgres:
    image: postgres:14
    container_name: postgres-fileVault
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filevault
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/filevault

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80" # maps localhost:3000 -> container's nginx port 80
    depends_on:
      - backend

volumes:
  pgdata:
